apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apps
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/a-bigelow/argocd-demo'
    path: apps
    targetRevision: HEAD
    helm:
      valueFiles:
        - env/demo/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
