apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: '5.52.1'
    chart: argo-cd
    helm:
      values: |
              {{- toYaml .Values.argo | nindent 8 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
