{{ if .Values.opsDashboard.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-dashboard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://christianknell.github.io/helm-charts'
    targetRevision: '3.5.0'
    chart: kube-ops-view
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-ops-view
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      annotations:
        istio-injection: enabled
      labels:
        marco: polo
    automated:
      prune: true
      selfHeal: true
  {{ end }}