apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://stefanprodan.github.io/podinfo'
    targetRevision: '5.2.1'
    chart: podinfo
{{/*    helm:*/}}
{{/*      valueFiles:*/}}
{{/*        - values.yaml*/}}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
