apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://stefanprodan.github.io/podinfo'
    targetRevision: '6.5.4'
    chart: podinfo
    helm:
      values: |
        key: ui.message
        value: {{ .Values.podInfo.message }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
