{{ if .Values.podInfo.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://stefanprodan.github.io/podinfo'
    targetRevision: '6.5.4'
    chart: podinfo
    helm:
      values: |
              {{- toYaml .Values.podInfo | nindent 8 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: podinfo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      annotations:
        istio-injection: enabled
      labels:
        ping: pong
    automated:
      prune: true
      selfHeal: true
  {{ end }}